# Generated by Django 5.2.3 on 2025-07-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
