# Generated by Django 5.2.3 on 2025-07-13 00:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_maintenancepackage_maintenancecontract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('building_floors', models.IntegerField()),
                ('building_type', models.CharField(max_length=50)),
                ('elevator_age', models.CharField(max_length=50)),
                ('elevator_count', models.IntegerField()),
                ('coverage_level', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_contracts', to=settings.AUTH_USER_MODEL)),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.insurancetype')),
            ],
        ),
    ]
